# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_commentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='UpvoteModel',
        ),
    ]
