# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170729_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvotemodel',
            name='post',
        ),
        migrations.RemoveField(
            model_name='upvotemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='upvote_num',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='UpvoteModel',
        ),
    ]
